<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-DUJFBR3O" failures="1" tests="1" name="Edge on macOS Ventura" time="36.525" errors="0" timestamp="2024-12-08T11:55:16 IST">
  <testcase classname="LT_TestNg_Project.TestScenarios.LambdaTestCertifications" name="testScenarios" time="9.682">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]
at LT_TestNg_Project.TestScenarios.LambdaTestCertifications.testScenarios(LambdaTestCertifications.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testScenarios -->
</testsuite> <!-- Edge on macOS Ventura -->
